[package]
name = "rocket_okapi"
description = "OpenAPI (AKA Swagger) document generation for Rocket applications"
repository = "https://github.com/GREsau/okapi"
version = "0.6.0-alpha-1"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "openapi", "swagger", "rocket"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", default-features = false }
schemars = { version = "0.8.0-alpha-4" }
okapi = { version = "0.5.0-alpha-1", path = "../okapi" }
rocket_okapi_codegen = { version = "=0.6.0-alpha-1", path = "../rocket-okapi-codegen" }
serde = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
default-features = false
features = ["json"]
