[package]
name = "rocket_okapi_codegen"
description = "Macros supporting rocket_okapi"
repository = "https://github.com/GREsau/okapi"
version = "0.3.1"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "openapi", "swagger", "rocket"]

[lib]
proc-macro = true

[dependencies]
rocket_http = "0.4.2"
darling = "0.10"
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
