[package]
name = "json_web_api"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"

[dependencies]
schemars = "0.6.1"
okapi = { version = "0.3.0", path = "../../okapi" }
rocket_okapi = { version = "0.3.0", path = "../../rocket-okapi" }
rocket = { version = "0.4.3", default-features = false }
serde = "1.0"

[dependencies.rocket_contrib]
version = "0.4.3"
default-features = false
features = ["json"]

