[package]
name = "json_web_api"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"

[dependencies]
schemars = "0.7.0"
okapi = { version = "0.4.0", path = "../../okapi" }
rocket_okapi = { version = "0.5.1", path = "../../rocket-okapi" }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master", default-features = false }
serde = "1.0"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
branch = "master"
default-features = false
features = ["json"]

